project_id = "cxjtdkpmimsumezzifxv"

[functions.fetch-pois]
verify_jwt = true

[functions.analyze-walk]
verify_jwt = true

[functions.geocode]
verify_jwt = true

[functions.detect-stops]
verify_jwt = true

[functions.get-weather]
verify_jwt = false
